import argparse
import os
import sys

import numpy as np
import plotly.graph_objects as go
from plotly.colors import qualitative


def parse_args():
	parser = argparse.ArgumentParser(
		description="Convert a saved 3D state t-SNE result into an interactive Plotly HTML file"
	)
	parser.add_argument(
		"--input",
		type=str,
		required=True,
		help="NPZ file generated by online_continual.tsne with --tsne_dim 3.",
	)
	parser.add_argument(
		"--output",
		type=str,
		default=None,
		help="Output HTML path; defaults to the input filename with .html.",
	)
	parser.add_argument("--point_size", type=float, default=2.0)
	parser.add_argument("--point_opacity", type=float, default=0.2)
	parser.add_argument("--endpoint_size", type=float, default=8.0)
	parser.add_argument("--endpoint_opacity", type=float, default=1.0)
	parser.add_argument("--line_width", type=float, default=1.0)
	parser.add_argument("--line_opacity", type=float, default=0.12)
	parser.add_argument(
		"--no_trajectory_lines",
		action="store_true",
		help="Draw state points without connecting steps from the same trajectory.",
	)
	args = parser.parse_args()

	args.input = os.path.abspath(args.input)
	args.output = os.path.abspath(args.output or os.path.splitext(args.input)[0] + ".html")
	if not os.path.isfile(args.input):
		parser.error(f"Input file does not exist: {args.input}")
	for name in ("point_size", "endpoint_size"):
		if getattr(args, name) <= 0:
			parser.error(f"--{name} must be positive")
	if args.line_width <= 0:
		parser.error("--line_width must be positive")
	for name in ("point_opacity", "endpoint_opacity", "line_opacity"):
		value = getattr(args, name)
		if not 0.0 <= value <= 1.0:
			parser.error(f"--{name} must be between 0 and 1")
	return args


def load_tsne_data(path):
	required_keys = {"tsne", "task_names", "episode_indices", "step_indices"}
	with np.load(path) as archive:
		missing = required_keys.difference(archive.files)
		if missing:
			raise KeyError(f"Missing arrays in {path}: {', '.join(sorted(missing))}")
		data = {key: archive[key] for key in archive.files}

	embedding = np.asarray(data["tsne"])
	if embedding.ndim != 2 or embedding.shape[1] != 3:
		raise ValueError(
			f"Expected a 3D t-SNE array with shape (N, 3), got {embedding.shape}. "
			"Regenerate it with --tsne_dim 3."
		)

	sample_count = len(embedding)
	for key in required_keys - {"tsne"}:
		if len(data[key]) != sample_count:
			raise ValueError(
				f"Array '{key}' has {len(data[key])} entries, expected {sample_count}."
			)
	data.setdefault("stage_indices", np.zeros(sample_count, dtype=np.int32))
	data.setdefault("episode_successes", np.zeros(sample_count, dtype=np.bool_))
	data.setdefault("checkpoints", np.full(sample_count, ""))
	return data


def trajectory_endpoint_masks(mask, episode_indices, step_indices):
	start_mask = np.zeros(mask.shape, dtype=np.bool_)
	end_mask = np.zeros(mask.shape, dtype=np.bool_)
	for episode_idx in np.unique(episode_indices[mask]):
		indices = np.flatnonzero(mask & (episode_indices == episode_idx))
		indices = indices[np.argsort(step_indices[indices])]
		start_mask[indices[0]] = True
		end_mask[indices[-1]] = True
	return start_mask, end_mask


def add_state_markers(
	figure,
	embedding,
	point_indices,
	episode_indices,
	step_indices,
	episode_successes,
	checkpoints,
	task_name,
	stage_idx,
	color,
	name,
	legend_group,
	point_role,
	size,
	opacity,
	symbol,
	outline_width=0,
):
	if len(point_indices) == 0:
		return
	points = embedding[point_indices]
	custom_data = np.column_stack(
		(
			episode_indices[point_indices],
			step_indices[point_indices],
			episode_successes[point_indices],
			checkpoints[point_indices],
		)
	)
	marker = {
		"size": size,
		"color": color,
		"opacity": opacity,
		"symbol": symbol,
	}
	if outline_width > 0:
		marker["line"] = {"color": "#111827", "width": outline_width}
	figure.add_trace(
		go.Scatter3d(
			x=points[:, 0],
			y=points[:, 1],
			z=points[:, 2],
			mode="markers",
			name=name,
			legendgroup=legend_group,
			marker=marker,
			customdata=custom_data,
			hovertemplate=(
				f"task={task_name}<br>"
				f"stage={stage_idx}<br>"
				f"point={point_role}<br>"
				"episode=%{customdata[0]}<br>"
				"step=%{customdata[1]}<br>"
				"success=%{customdata[2]}<br>"
				"checkpoint=%{customdata[3]}<br>"
				"t-SNE=(%{x:.2f}, %{y:.2f}, %{z:.2f})"
				"<extra></extra>"
			),
		)
	)


def add_trajectory_lines(
	figure,
	embedding,
	mask,
	episode_indices,
	step_indices,
	color,
	line_width,
	line_opacity,
	legend_group,
):
	for episode_idx in np.unique(episode_indices[mask]):
		trajectory_mask = mask & (episode_indices == episode_idx)
		indices = np.flatnonzero(trajectory_mask)
		indices = indices[np.argsort(step_indices[indices])]
		trajectory = embedding[indices]
		figure.add_trace(
			go.Scatter3d(
				x=trajectory[:, 0],
				y=trajectory[:, 1],
				z=trajectory[:, 2],
				mode="lines",
				line={"color": color, "width": line_width},
				opacity=line_opacity,
				hoverinfo="skip",
				showlegend=False,
				legendgroup=legend_group,
			)
		)


def build_figure(data, args):
	embedding = data["tsne"]
	task_names = data["task_names"].astype(str)
	stage_indices = data["stage_indices"]
	episode_indices = data["episode_indices"]
	step_indices = data["step_indices"]
	episode_successes = data["episode_successes"]
	checkpoints = data["checkpoints"].astype(str)
	unique_pairs = list(dict.fromkeys(zip(stage_indices.tolist(), task_names.tolist())))
	unique_stages = set(stage_indices.tolist())
	colors = qualitative.Plotly + qualitative.Safe + qualitative.Dark24

	figure = go.Figure()
	for pair_idx, (stage_idx, task_name) in enumerate(unique_pairs):
		mask = (stage_indices == stage_idx) & (task_names == task_name)
		color = colors[pair_idx % len(colors)]
		legend_group = f"{stage_idx}:{task_name}"
		label = task_name if len(unique_stages) == 1 else f"stage {stage_idx}: {task_name}"

		if not args.no_trajectory_lines:
			add_trajectory_lines(
				figure,
				embedding,
				mask,
				episode_indices,
				step_indices,
				color,
				args.line_width,
				args.line_opacity,
				legend_group,
			)

		start_mask, end_mask = trajectory_endpoint_masks(
			mask,
			episode_indices,
			step_indices,
		)
		middle_mask = mask & ~start_mask & ~end_mask
		add_state_markers(
			figure,
			embedding,
			np.flatnonzero(middle_mask),
			episode_indices,
			step_indices,
			episode_successes,
			checkpoints,
			task_name,
			stage_idx,
			color,
			label,
			legend_group,
			"intermediate",
			args.point_size,
			args.point_opacity,
			"circle",
		)
		add_state_markers(
			figure,
			embedding,
			np.flatnonzero(start_mask),
			episode_indices,
			step_indices,
			episode_successes,
			checkpoints,
			task_name,
			stage_idx,
			color,
			f"{label}: step 0",
			legend_group,
			"start",
			args.endpoint_size,
			args.endpoint_opacity,
			"diamond",
			1.5,
		)
		add_state_markers(
			figure,
			embedding,
			np.flatnonzero(end_mask),
			episode_indices,
			step_indices,
			episode_successes,
			checkpoints,
			task_name,
			stage_idx,
			color,
			f"{label}: final step",
			legend_group,
			"end",
			max(args.endpoint_size - 2.0, 1.0),
			args.endpoint_opacity,
			"x",
			1.5,
		)

	figure.update_layout(
		title="State representations from task trajectories",
		template="plotly_white",
		height=850,
		margin={"l": 0, "r": 0, "b": 0, "t": 55},
		legend={"itemsizing": "constant"},
		scene={
			"xaxis_title": "t-SNE 1",
			"yaxis_title": "t-SNE 2",
			"zaxis_title": "t-SNE 3",
			"aspectmode": "data",
		},
	)
	return figure


def main():
	args = parse_args()
	data = load_tsne_data(args.input)
	figure = build_figure(data, args)
	os.makedirs(os.path.dirname(args.output), exist_ok=True)
	figure.write_html(
		args.output,
		include_plotlyjs=True,
		full_html=True,
		config={
			"displaylogo": False,
			"scrollZoom": True,
			"toImageButtonOptions": {"format": "png", "scale": 2},
		},
	)
	print("input:", args.input)
	print("points:", len(data["tsne"]))
	print("plot:", args.output)


if __name__ == "__main__":
	sys.exit(main())


'''
cd Fetch/quasimetric-rl
conda activate RLL3

python -m online_continual.tsne_plotly \
  --input online_continual/results/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse_final_success_state_tsne_3d.npz


 python -m online_continual.tsne_plotly \
  --input online_continual/results/fetch_continual_push-slide_seed0_buffer_gc-sparse_slide-scale0.8/fetch_continual_push-slide_seed0_buffer_gc-sparse_slide-scale0.8_final_success_state_tsne_3d.npz

 python -m online_continual.tsne_plotly \
   --input online_continual/results/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse_final_state_tsne_3d.npz
  
  python -m online_continual.tsne_plotly \
   --input online_continual/results/fetch_continual_push-slide_seed0_buffer_gc-sparse_slide-scale0.8/fetch_continual_push-slide_seed0_buffer_gc-sparse_slide-scale0.8_final_state_tsne_3d.npz
  
  python -m online_continual.tsne_plotly \
     --input online_continual/results/fetch_continual_push-slide_seed0_buffer_gc-sparse_slide-scale0.8/fetch_continual_push-slide_seed0_buffer_gc-sparse_slide-scale0.8_final_state_tsne_3d.npz
   
	 python -m online_continual.tsne_plotly \
		 --input online_continual/results/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse_final_robot_state_tsne_3d.npz

		python -m online_continual.tsne_plotly \
				 --input online_continual/results/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse_final_robot_state_tsne_3d.npz
	python -m online_continual.tsne.tsne_plotly \
		--input online_continual/results/cqrl_wd/fetch_cqrl_push-slide-pick-and-place_seed0_gc-sparse_slide-scale0.795/fetch_cqrl_push-slide-pick-and-place_seed0_gc-sparse_slide-scale0.795_final_success_robot_state_tsne_3d.npz
		--input online_continual/results/cqrl_wd/fetch_cqrl_push-slide-pick-and-place_seed0_gc-sparse_slide-scale0.795/fetch_cqrl_push-slide-pick-and-place_seed0_gc-sparse_slide-scale0.795_final_robot_state_tsne_3d.npz

  
  '''