import argparse
import os
import sys

import numpy as np
import plotly.graph_objects as go
from plotly.colors import qualitative


def parse_args():
	parser = argparse.ArgumentParser(
		description="Convert a saved 3D state t-SNE result into an interactive Plotly HTML file"
	)
	parser.add_argument(
		"--input",
		type=str,
		required=True,
		help="NPZ file generated by online_continual.tsne with --tsne_dim 3.",
	)
	parser.add_argument(
		"--output",
		type=str,
		default=None,
		help="Output HTML path; defaults to the input filename with .html.",
	)
	parser.add_argument("--point_size", type=float, default=2.0)
	parser.add_argument("--point_opacity", type=float, default=0.2)
	parser.add_argument("--start_opacity", type=float, default=1.0)
	parser.add_argument("--line_width", type=float, default=1.0)
	parser.add_argument("--line_opacity", type=float, default=0.12)
	parser.add_argument(
		"--shared_neighbors",
		type=int,
		default=60,
		help="Number of local t-SNE neighbors used to measure task overlap.",
	)
	parser.add_argument(
		"--shared_min_fraction",
		type=float,
		default=0.15,
		help="Minimum fraction required from every task in a shared neighborhood.",
	)
	parser.add_argument("--shared_point_size", type=float, default=5.0)
	parser.add_argument("--shared_point_opacity", type=float, default=0.95)
	parser.add_argument(
		"--no_trajectory_lines",
		action="store_true",
		help="Draw state points without connecting steps from the same trajectory.",
	)
	args = parser.parse_args()

	args.input = os.path.abspath(args.input)
	args.output = os.path.abspath(args.output or os.path.splitext(args.input)[0] + "_shared.html")
	if not os.path.isfile(args.input):
		parser.error(f"Input file does not exist: {args.input}")
	for name in ("point_size", "shared_point_size"):
		if getattr(args, name) <= 0:
			parser.error(f"--{name} must be positive")
	if args.line_width <= 0:
		parser.error("--line_width must be positive")
	if args.shared_neighbors <= 0:
		parser.error("--shared_neighbors must be positive")
	if not 0.0 < args.shared_min_fraction <= 1.0:
		parser.error("--shared_min_fraction must be in (0, 1]")
	for name in (
		"point_opacity",
		"start_opacity",
		"line_opacity",
		"shared_point_opacity",
	):
		value = getattr(args, name)
		if not 0.0 <= value <= 1.0:
			parser.error(f"--{name} must be between 0 and 1")
	return args


def load_tsne_data(path):
	required_keys = {"tsne", "task_names", "episode_indices", "step_indices"}
	with np.load(path) as archive:
		missing = required_keys.difference(archive.files)
		if missing:
			raise KeyError(f"Missing arrays in {path}: {', '.join(sorted(missing))}")
		data = {key: archive[key] for key in archive.files}

	embedding = np.asarray(data["tsne"])
	if embedding.ndim != 2 or embedding.shape[1] != 3:
		raise ValueError(
			f"Expected a 3D t-SNE array with shape (N, 3), got {embedding.shape}. "
			"Regenerate it with --tsne_dim 3."
		)

	sample_count = len(embedding)
	for key in required_keys - {"tsne"}:
		if len(data[key]) != sample_count:
			raise ValueError(
				f"Array '{key}' has {len(data[key])} entries, expected {sample_count}."
			)
	data.setdefault("stage_indices", np.zeros(sample_count, dtype=np.int32))
	data.setdefault("episode_successes", np.zeros(sample_count, dtype=np.bool_))
	data.setdefault("checkpoints", np.full(sample_count, ""))
	return data


def find_shared_region(embedding, task_names, neighbors, min_fraction):
	try:
		from sklearn.neighbors import NearestNeighbors
	except ImportError as error:
		raise ImportError("Install scikit-learn to detect shared t-SNE regions.") from error

	unique_tasks = list(dict.fromkeys(task_names.tolist()))
	task_count = len(unique_tasks)
	if task_count < 2:
		raise ValueError("Shared-region detection needs at least two tasks.")
	if min_fraction > 1.0 / task_count:
		raise ValueError(
			f"--shared_min_fraction cannot exceed {1.0 / task_count:.3f} "
			f"when comparing {task_count} tasks."
		)
	if len(embedding) <= task_count:
		raise ValueError("Not enough t-SNE samples to detect a shared region.")

	effective_neighbors = min(int(neighbors), len(embedding) - 1)
	if effective_neighbors < task_count:
		raise ValueError(
			f"--shared_neighbors must be at least the number of tasks ({task_count})."
		)
	neighbor_indices = NearestNeighbors(n_neighbors=effective_neighbors).fit(
		embedding
	).kneighbors(return_distance=False)
	neighbor_tasks = task_names[neighbor_indices]
	task_fractions = np.column_stack(
		[(neighbor_tasks == task_name).mean(axis=1) for task_name in unique_tasks]
	)
	shared_scores = task_fractions.min(axis=1)
	return {
		"mask": shared_scores >= min_fraction,
		"scores": shared_scores,
		"task_fractions": task_fractions,
		"task_names": unique_tasks,
		"neighbors": effective_neighbors,
	}


def trajectory_endpoint_masks(mask, episode_indices, step_indices):
	start_mask = np.zeros(mask.shape, dtype=np.bool_)
	end_mask = np.zeros(mask.shape, dtype=np.bool_)
	for episode_idx in np.unique(episode_indices[mask]):
		indices = np.flatnonzero(mask & (episode_indices == episode_idx))
		indices = indices[np.argsort(step_indices[indices])]
		start_mask[indices[0]] = True
		end_mask[indices[-1]] = True
	return start_mask, end_mask


def add_state_markers(
	figure,
	embedding,
	point_indices,
	episode_indices,
	step_indices,
	episode_successes,
	checkpoints,
	task_name,
	stage_idx,
	color,
	name,
	legend_group,
	point_role,
	size,
	opacity,
	symbol,
	outline_width=0,
):
	if len(point_indices) == 0:
		return
	points = embedding[point_indices]
	custom_data = np.column_stack(
		(
			episode_indices[point_indices],
			step_indices[point_indices],
			episode_successes[point_indices],
			checkpoints[point_indices],
		)
	)
	marker = {
		"size": size,
		"color": color,
		"opacity": opacity,
		"symbol": symbol,
	}
	if outline_width > 0:
		marker["line"] = {"color": "#111827", "width": outline_width}
	figure.add_trace(
		go.Scatter3d(
			x=points[:, 0],
			y=points[:, 1],
			z=points[:, 2],
			mode="markers",
			name=name,
			legendgroup=legend_group,
			marker=marker,
			customdata=custom_data,
			hovertemplate=(
				f"task={task_name}<br>"
				f"stage={stage_idx}<br>"
				f"point={point_role}<br>"
				"episode=%{customdata[0]}<br>"
				"step=%{customdata[1]}<br>"
				"success=%{customdata[2]}<br>"
				"checkpoint=%{customdata[3]}<br>"
				"t-SNE=(%{x:.2f}, %{y:.2f}, %{z:.2f})"
				"<extra></extra>"
			),
		)
	)


def add_shared_region_markers(
	figure,
	data,
	shared_region,
	point_mask,
	args,
):
	point_indices = np.flatnonzero(point_mask)
	if len(point_indices) == 0:
		return

	embedding = data["tsne"]
	task_names = data["task_names"].astype(str)
	episode_indices = data["episode_indices"]
	step_indices = data["step_indices"]
	episode_successes = data["episode_successes"]
	shared_scores = shared_region["scores"]
	task_fractions = shared_region["task_fractions"]
	shared_tasks = shared_region["task_names"]
	custom_data = np.empty((len(point_indices), 5 + len(shared_tasks)), dtype=object)
	custom_data[:, 0] = task_names[point_indices]
	custom_data[:, 1] = episode_indices[point_indices]
	custom_data[:, 2] = step_indices[point_indices]
	custom_data[:, 3] = episode_successes[point_indices]
	custom_data[:, 4] = shared_scores[point_indices]
	custom_data[:, 5:] = task_fractions[point_indices]
	fraction_hover = "".join(
		f"local {task_name}=%{{customdata[{5 + task_idx}]:.2f}}<br>"
		for task_idx, task_name in enumerate(shared_tasks)
	)
	figure.add_trace(
		go.Scatter3d(
			x=embedding[point_indices, 0],
			y=embedding[point_indices, 1],
			z=embedding[point_indices, 2],
			mode="markers",
			name=f"shared by all {len(shared_tasks)} tasks",
			legendgroup="shared-region",
			marker={
				"size": args.shared_point_size,
				"color": shared_scores[point_indices],
				"colorscale": [
					[0.0, "#fde68a"],
					[0.5, "#f59e0b"],
					[1.0, "#b91c1c"],
				],
				"cmin": args.shared_min_fraction,
				"cmax": 1.0 / len(shared_tasks),
				"opacity": args.shared_point_opacity,
				"symbol": "circle",
				"line": {"color": "#422006", "width": 0.8},
				"colorbar": {"title": "min local<br>task fraction", "thickness": 14},
			},
			customdata=custom_data,
			hovertemplate=(
				"shared region<br>"
				"source task=%{customdata[0]}<br>"
				"episode=%{customdata[1]}<br>"
				"step=%{customdata[2]}<br>"
				"success=%{customdata[3]}<br>"
				"overlap score=%{customdata[4]:.2f}<br>"
				+ fraction_hover
				+ "t-SNE=(%{x:.2f}, %{y:.2f}, %{z:.2f})<extra></extra>"
			),
		)
	)


def add_trajectory_lines(
	figure,
	embedding,
	mask,
	episode_indices,
	step_indices,
	color,
	line_width,
	line_opacity,
	legend_group,
):
	for episode_idx in np.unique(episode_indices[mask]):
		trajectory_mask = mask & (episode_indices == episode_idx)
		indices = np.flatnonzero(trajectory_mask)
		indices = indices[np.argsort(step_indices[indices])]
		trajectory = embedding[indices]
		figure.add_trace(
			go.Scatter3d(
				x=trajectory[:, 0],
				y=trajectory[:, 1],
				z=trajectory[:, 2],
				mode="lines",
				line={"color": color, "width": line_width},
				opacity=line_opacity,
				hoverinfo="skip",
				showlegend=False,
				legendgroup=legend_group,
			)
		)


def build_figure(data, shared_region, args):
	embedding = data["tsne"]
	task_names = data["task_names"].astype(str)
	stage_indices = data["stage_indices"]
	episode_indices = data["episode_indices"]
	step_indices = data["step_indices"]
	episode_successes = data["episode_successes"]
	checkpoints = data["checkpoints"].astype(str)
	unique_pairs = list(dict.fromkeys(zip(stage_indices.tolist(), task_names.tolist())))
	unique_stages = set(stage_indices.tolist())
	colors = qualitative.Plotly + qualitative.Safe + qualitative.Dark24
	shared_mask = shared_region["mask"]
	all_start_mask = np.zeros(len(embedding), dtype=np.bool_)

	figure = go.Figure()
	for pair_idx, (stage_idx, task_name) in enumerate(unique_pairs):
		mask = (stage_indices == stage_idx) & (task_names == task_name)
		color = colors[pair_idx % len(colors)]
		legend_group = f"{stage_idx}:{task_name}"
		label = task_name if len(unique_stages) == 1 else f"stage {stage_idx}: {task_name}"

		if not args.no_trajectory_lines:
			add_trajectory_lines(
				figure,
				embedding,
				mask,
				episode_indices,
				step_indices,
				color,
				args.line_width,
				args.line_opacity,
				legend_group,
			)

		start_mask, _ = trajectory_endpoint_masks(
			mask,
			episode_indices,
			step_indices,
		)
		all_start_mask |= start_mask
		trajectory_mask = mask & ~start_mask & ~shared_mask
		add_state_markers(
			figure,
			embedding,
			np.flatnonzero(trajectory_mask),
			episode_indices,
			step_indices,
			episode_successes,
			checkpoints,
			task_name,
			stage_idx,
			color,
			label,
			legend_group,
			"trajectory",
			args.point_size,
			args.point_opacity,
			"circle",
		)
		add_state_markers(
			figure,
			embedding,
			np.flatnonzero(start_mask),
			episode_indices,
			step_indices,
			episode_successes,
			checkpoints,
			task_name,
			stage_idx,
			color,
			f"{label}: step 0",
			legend_group,
			"start",
			args.point_size,
			args.start_opacity,
			"circle",
		)

	add_shared_region_markers(
		figure,
		data,
		shared_region,
		shared_mask & ~all_start_mask,
		args,
	)

	figure.update_layout(
		title=(
			f"Shared state region across {len(shared_region['task_names'])} tasks"
			f"<br><sup>k={shared_region['neighbors']}, minimum local task fraction="
			f"{args.shared_min_fraction:g}</sup>"
		),
		template="plotly_white",
		height=850,
		margin={"l": 0, "r": 0, "b": 0, "t": 55},
		legend={"itemsizing": "constant"},
		scene={
			"xaxis_title": "t-SNE 1",
			"yaxis_title": "t-SNE 2",
			"zaxis_title": "t-SNE 3",
			"aspectmode": "data",
		},
	)
	return figure


def main():
	args = parse_args()
	data = load_tsne_data(args.input)
	shared_region = find_shared_region(
		data["tsne"],
		data["task_names"].astype(str),
		args.shared_neighbors,
		args.shared_min_fraction,
	)
	figure = build_figure(data, shared_region, args)
	os.makedirs(os.path.dirname(args.output), exist_ok=True)
	figure.write_html(
		args.output,
		include_plotlyjs=True,
		full_html=True,
		config={
			"displaylogo": False,
			"scrollZoom": True,
			"toImageButtonOptions": {"format": "png", "scale": 2},
		},
	)
	print("input:", args.input)
	print("points:", len(data["tsne"]))
	print("shared points:", int(shared_region["mask"].sum()))
	for task_name in shared_region["task_names"]:
		task_mask = data["task_names"].astype(str) == task_name
		print(
			f"  {task_name}:",
			int(np.sum(shared_region["mask"] & task_mask)),
		)
	print("plot:", args.output)


if __name__ == "__main__":
	sys.exit(main())


'''
cd Fetch/quasimetric-rl
conda activate RLL3

python -m online_continual.tsne_plotly \
  --input online_continual/results/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse_final_success_state_tsne_3d.npz


 python -m online_continual.tsne_plotly \
  --input online_continual/results/fetch_continual_push-slide_seed0_buffer_gc-sparse_slide-scale0.8/fetch_continual_push-slide_seed0_buffer_gc-sparse_slide-scale0.8_final_success_state_tsne_3d.npz

 python -m online_continual.tsne_plotly \
   --input online_continual/results/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse_final_state_tsne_3d.npz
  
  python -m online_continual.tsne_plotly \
   --input online_continual/results/fetch_continual_push-slide_seed0_buffer_gc-sparse_slide-scale0.8/fetch_continual_push-slide_seed0_buffer_gc-sparse_slide-scale0.8_final_state_tsne_3d.npz
  
  python -m online_continual.tsne_plotly \
     --input online_continual/results/fetch_continual_push-slide_seed0_buffer_gc-sparse_slide-scale0.8/fetch_continual_push-slide_seed0_buffer_gc-sparse_slide-scale0.8_final_state_tsne_3d.npz
   
	 python -m online_continual.tsne_plotly \
		 --input online_continual/results/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse_final_robot_state_tsne_3d.npz

		python -m online_continual.tsne_plotly \
				 --input online_continual/results/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse/fetch_continual_push-pick-and-place_seed0_buffer_gc-sparse_final_robot_state_tsne_3d.npz
	python -m online_continual.tsne.tsne_plotly \
		--input online_continual/results/cqrl_wd/fetch_cqrl_push-slide-pick-and-place_seed0_gc-sparse_slide-scale0.795/fetch_cqrl_push-slide-pick-and-place_seed0_gc-sparse_slide-scale0.795_final_success_robot_state_tsne_3d.npz
		--input online_continual/results/cqrl_wd/fetch_cqrl_push-slide-pick-and-place_seed0_gc-sparse_slide-scale0.795/fetch_cqrl_push-slide-pick-and-place_seed0_gc-sparse_slide-scale0.795_final_robot_state_tsne_3d.npz

  
  '''